# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  app-postman

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 600  # 10 minutes
    MemorySize: 512

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:

  AppDevPostman:
    # This is the Lambda function definition. For all available properties, see
    # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Type: AWS::Serverless::Function
    Properties:
      Description: Run postman collection
      CodeUri: src/
      Handler: newman_run.handler
      Environment:
        Variables:
          CONFIG_FILE: config/app_dev.json
          NODE_ENV: app_dev
          STAGE: development
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: rate(6 hours)
      Layers:
        # Ref name is generated by TitleCasing
        # the layer name & appending LambdaLayer
        - { Ref: NewmanLibsLambdaLayer }
      # This property associates this Lambda function with a scheduled CloudWatch Event. For all available properties, see
      # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#schedule

  # TODO: confirm how SAM builds a layer and what it does with buildspec.yml
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-layerversion.html
  NewmanLibsLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: nodejs12.x
    Properties:
      LayerName: NewmanLibs
      Description: Dependencies for postman tests
      ContentUri: layer/
      CompatibleRuntimes:
        - nodejs12.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
